language: php

php:
  - 5.3
  - 5.4
  - hhvm

before_script:
  - wget -nc http://getcomposer.org/composer.phar
  - php composer.phar update
  - mkdir tests/Seine/Writer/_tmp

script: phpunit --configuration tests/phpunit.travis.xml